# Find more information on toml format here:  https://github.com/toml-lang/toml
modLoader="javafml"
loaderVersion="[40,)"
license="GNU GPLv3"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="distill" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${version}" #mandatory
displayName="Distill" #mandatory
displayURL="https://github.com/boredhero/distill/tree/1.18.2-dev" #optional
logoFile="distill.png" #optional
authors="Noah Martino a.k.a boredhero" #optional
description='''
Distill - A new take on the concept of potions

Completely replace (or augment) the potion system with realistic alcoholic concoctions

But beware, you may not like the consequences of your actions!
'''
# Here's another dependency
[[dependencies.distill]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
